name: Assign Code Reviewer

on:
    pull_request:
        branches: ['master']
    # pull_request:
    #     types:
    #         - opened
jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  reviewers: |
                      if [[ "${{ github.actor }}" == "MusinRamil" ]]; then
                        reviewer="barsukov-d"
                      elif [[ "${{ github.actor }}" == "barsukov-d" ]]; then
                        reviewer="MusinRamil"
                      else
                        reviewer="MusinRamil"
                      fi
                  assignees: ${{ github.actor }}
                  numOfAssignee: 1
