name: Assign Code Reviewer

on:
    pull_request:
        branches: ['master']
    # pull_request:
    #     types:
    #         - opened

jobs:
    assign_reviewer:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR author
              id: check_author
              run: |
                  PR_AUTHOR=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
                  if [[ "$PR_AUTHOR" == "MusinRamil" ]]; then
                    echo "barsukov-d" > reviewer.txt
                  elif [[ "$PR_AUTHOR" == "barsukov-d" ]]; then
                    echo "MusinRamil" > reviewer.txt
                  else
                    echo "Skipping review assignment."
                    exit 0
                  fi

            - name: Read Reviewer
              id: read_reviewer
              run: |
                  REVIEWER=$(cat reviewer.txt)
                  echo "::set-output name=reviewer::$REVIEWER"

            - name: Assign Reviewer
              uses: octokit/auth-action@v2.x
              id: auth
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Request Reviewer
              uses: octokit/request-action@v2.x
              with:
                  route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
                  mediaType: '{"previews":["sailor-v-preview"]}'
                  token: ${{ steps.auth.outputs.token }}
                  reviewers: ${{ steps.read_reviewer.outputs.reviewer }}
