name: Assign Code Reviewer

on:
    pull_request:
        branches: ['master']
    # pull_request:
    #     types:
    #         - opened

jobs:
    assign_reviewer:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR author
              id: check_author
              run: |
                  PR_AUTHOR=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
                  if [[ "$PR_AUTHOR" == "MusinRamil" ]]; then
                    echo "barsukov-d" >> $GITHUB_ENV
                  elif [[ "$PR_AUTHOR" == "barsukov-d" ]]; then
                    echo "MusinRamil" >> $GITHUB_ENV
                  else
                    echo "Skipping review assignment."
                    exit 0
                  fi

            - name: Assign Reviewer
              uses: octokit/request-action@v2.x
              with:
                  route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
                  headers: |
                      Authorization: token ${{ secrets.GITHUB_TOKEN }}
                  body: |
                      {
                        "reviewers": ["${{ env.REVIEWER }}"]
                      }
