name: Assign Code Reviewer

on:
    pull_request:
        branches: ['master']
    # pull_request:
    #     types:
    #         - opened

jobs:
    assign_reviewer:
        runs-on: ubuntu-latest
        steps:
            - uses: hkusu/review-assign-action@v1
              with:
                  assignees: ${{ github.actor }}
                  reviewers: MusinRamil, barsukov-d
