name: Auto Assign

on:
    pull_request:
        branches: ['master']

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Auto Assign
              uses: wow-actions/auto-assign@v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  reviewers: |
                      barsukov-d
                      MusinRamil
                  assignees: ${{ github.actor }}
                  skipKeywords: draft
